"""create normalized clinical case tables"""
from alembic import op
import sqlalchemy as sa


revision = '4975e664eeb0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clinical_cases',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=False),
    sa.Column('vignette', sa.Text(), nullable=False),
    sa.Column('age_years', sa.Integer(), nullable=True),
    sa.Column('reference_diagnosis', sa.String(length=200), nullable=False),
    sa.Column('normalized_reference_diagnosis', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('age_years IS NULL OR age_years BETWEEN 0 AND 120', name='ck_case_age'),
    sa.CheckConstraint('char_length(normalized_reference_diagnosis) > 0', name='ck_case_normalized_reference'),
    sa.CheckConstraint('char_length(reference_diagnosis) BETWEEN 1 AND 200', name='ck_case_reference'),
    sa.CheckConstraint('char_length(title) BETWEEN 1 AND 120', name='ck_case_title'),
    sa.CheckConstraint('char_length(vignette) BETWEEN 1 AND 8000', name='ck_case_vignette'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('clinical_case_accepted_answers',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('clinical_case_id', sa.Uuid(), nullable=False),
    sa.Column('answer', sa.String(length=200), nullable=False),
    sa.Column('normalized_answer', sa.Text(), nullable=False),
    sa.CheckConstraint('char_length(answer) BETWEEN 1 AND 200', name='ck_answer_text'),
    sa.CheckConstraint('char_length(normalized_answer) > 0', name='ck_answer_normalized'),
    sa.ForeignKeyConstraint(['clinical_case_id'], ['clinical_cases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('clinical_case_id', 'normalized_answer', name='uq_case_normalized_answer')
    )
    op.create_index(op.f('ix_clinical_case_accepted_answers_clinical_case_id'), 'clinical_case_accepted_answers', ['clinical_case_id'], unique=False)
    op.create_table('clinical_case_attempts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('clinical_case_id', sa.Uuid(), nullable=False),
    sa.Column('diagnosis', sa.String(length=200), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('is_correct', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('(is_correct AND score = 100) OR (NOT is_correct AND score = 0)', name='ck_attempt_consistency'),
    sa.CheckConstraint('char_length(diagnosis) BETWEEN 1 AND 200', name='ck_attempt_diagnosis'),
    sa.CheckConstraint('score IN (0, 100)', name='ck_attempt_score'),
    sa.ForeignKeyConstraint(['clinical_case_id'], ['clinical_cases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clinical_case_attempts_clinical_case_id'), 'clinical_case_attempts', ['clinical_case_id'], unique=False)
    op.create_table('clinical_case_symptoms',
    sa.Column('clinical_case_id', sa.Uuid(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(length=200), nullable=False),
    sa.CheckConstraint('char_length(text) BETWEEN 1 AND 200', name='ck_symptom_text'),
    sa.CheckConstraint('position BETWEEN 0 AND 19', name='ck_symptom_position'),
    sa.ForeignKeyConstraint(['clinical_case_id'], ['clinical_cases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('clinical_case_id', 'position')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('clinical_case_symptoms')
    op.drop_index(op.f('ix_clinical_case_attempts_clinical_case_id'), table_name='clinical_case_attempts')
    op.drop_table('clinical_case_attempts')
    op.drop_index(op.f('ix_clinical_case_accepted_answers_clinical_case_id'), table_name='clinical_case_accepted_answers')
    op.drop_table('clinical_case_accepted_answers')
    op.drop_table('clinical_cases')
    # ### end Alembic commands ###
